#!/usr/bin/env python3
"""Embed ui/index.html into the sketch as PROGMEM. One source of truth for the UI.

Run after editing the dashboard:  python3 tools/gen_page.py
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "ui" / "index.html"
DST = ROOT / "firmware" / "classroom_node" / "page.h"
DELIM = "HTML"

html = SRC.read_text(encoding="utf-8")
# A raw string literal ends at )HTML" — if the page ever contains that, the
# generated header silently breaks, so refuse rather than emit bad C++.
if f'){DELIM}"' in html:
    sys.exit(f'{SRC}: contains )"{DELIM}" which would terminate the raw literal early')

DST.write_text(
    "// Generated by tools/gen_page.py from ui/index.html. Do not edit by hand.\n"
    "#pragma once\n"
    "#include <pgmspace.h>\n\n"
    f'static const char INDEX_HTML[] PROGMEM = R"{DELIM}(' + html + f'){DELIM}";\n',
    encoding="utf-8",
)
print(f"{DST.relative_to(ROOT)}: {len(html)} bytes of HTML embedded")
